name: Pylint

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8"]
    
    steps:
    - uses: actions/checkout@v2
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
        PR: ${{ steps.findPr.outputs.pr }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        pip install PyGithub==1.43.8
    - name: Analysing the code with pylint
      run: |
        python main.py "${{ github.token }}" ${{ steps.findPr.outputs.pr }}
